vich_uploader:
    db_driver: orm

    mappings:
       plat_image:
           uri_prefix: /assets/images/plat_images
           upload_destination: '%kernel.project_dir%/public/assets/images/plat_images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
