<?php

namespace Container47xsyVg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SI0cRocService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sI0cRoc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sI0cRoc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'plat_repo' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
        ], [
            'plat_repo' => 'App\\Repository\\PlatRepository',
        ]);
    }
}
