<?php

namespace Container47xsyVg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9Q2_FGC.App\Entity\PlatImage' shared service.
     *
     * @return \App\Entity\PlatImage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9Q2_FGC": it references class "App\\Entity\\PlatImage" but no such service exists.');
    }
}
