<?php

namespace ContainerASEiCAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_81YDTlYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.81YDTlY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.81YDTlY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'message_repo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'users_repo' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'message_repo' => 'App\\Repository\\MessageRepository',
            'users_repo' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
