<?php

namespace ContainerASEiCAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9Q2FGCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Q2_FGC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Q2_FGC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'plat_image' => ['privates', '.errored..service_locator.9Q2_FGC.App\\Entity\\PlatImage', NULL, 'Cannot autowire service ".service_locator.9Q2_FGC": it references class "App\\Entity\\PlatImage" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'plat_image' => 'App\\Entity\\PlatImage',
        ]);
    }
}
