<?php

namespace ContainerASEiCAH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QEgFkqhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qEgFkqh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qEgFkqh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::delete_user' => ['privates', '.service_locator.meYWSv2', 'get_ServiceLocator_MeYWSv2Service', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.81YDTlY', 'get_ServiceLocator_81YDTlYService', true],
            'App\\Controller\\AdminController::update_role' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\HomeController::contact_message' => ['privates', '.service_locator.Nzwfc8r', 'get_ServiceLocator_Nzwfc8rService', true],
            'App\\Controller\\PlatController::add_image' => ['privates', '.service_locator.CTUb8ok', 'get_ServiceLocator_CTUb8okService', true],
            'App\\Controller\\PlatController::delete' => ['privates', '.service_locator.CTUb8ok', 'get_ServiceLocator_CTUb8okService', true],
            'App\\Controller\\PlatController::delete_image' => ['privates', '.service_locator.9Q2_FGC', 'get_ServiceLocator_9Q2FGCService', true],
            'App\\Controller\\PlatController::edit' => ['privates', '.service_locator.dEIufx.', 'get_ServiceLocator_DEIufx_Service', true],
            'App\\Controller\\PlatController::index' => ['privates', '.service_locator.sI0cRoc', 'get_ServiceLocator_SI0cRocService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.1lMksgj', 'get_ServiceLocator_1lMksgjService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:delete_user' => ['privates', '.service_locator.meYWSv2', 'get_ServiceLocator_MeYWSv2Service', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.81YDTlY', 'get_ServiceLocator_81YDTlYService', true],
            'App\\Controller\\AdminController:update_role' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\HomeController:contact_message' => ['privates', '.service_locator.Nzwfc8r', 'get_ServiceLocator_Nzwfc8rService', true],
            'App\\Controller\\PlatController:add_image' => ['privates', '.service_locator.CTUb8ok', 'get_ServiceLocator_CTUb8okService', true],
            'App\\Controller\\PlatController:delete' => ['privates', '.service_locator.CTUb8ok', 'get_ServiceLocator_CTUb8okService', true],
            'App\\Controller\\PlatController:delete_image' => ['privates', '.service_locator.9Q2_FGC', 'get_ServiceLocator_9Q2FGCService', true],
            'App\\Controller\\PlatController:edit' => ['privates', '.service_locator.dEIufx.', 'get_ServiceLocator_DEIufx_Service', true],
            'App\\Controller\\PlatController:index' => ['privates', '.service_locator.sI0cRoc', 'get_ServiceLocator_SI0cRocService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.1lMksgj', 'get_ServiceLocator_1lMksgjService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::delete_user' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::update_role' => '?',
            'App\\Controller\\HomeController::contact_message' => '?',
            'App\\Controller\\PlatController::add_image' => '?',
            'App\\Controller\\PlatController::delete' => '?',
            'App\\Controller\\PlatController::delete_image' => '?',
            'App\\Controller\\PlatController::edit' => '?',
            'App\\Controller\\PlatController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:delete_user' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:update_role' => '?',
            'App\\Controller\\HomeController:contact_message' => '?',
            'App\\Controller\\PlatController:add_image' => '?',
            'App\\Controller\\PlatController:delete' => '?',
            'App\\Controller\\PlatController:delete_image' => '?',
            'App\\Controller\\PlatController:edit' => '?',
            'App\\Controller\\PlatController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
